# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[4,)" # Require at least 1.14.x
# License is REQUIRED after 1.16
license='GNU GPLv3'

[[mods]]
modId="ae2additions"
version="0.0.0.0.1"
displayName="AE Additions"
credits="The AEAdditions dev team"
authors="MasterYodA"
description='''
A mod with helpful additions for Applied Energistics 2

Special credit for original mod authors M3gaFr3ak/DrummerMC and Textures by PaleoCrafter and Cyntain
'''
[[dependencies.ae2additions]]
modId="forge"
mandatory=true
versionRange="[47.0.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.ae2additions]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
[[dependencies.ae2additions]]
modId="ae2"
mandatory=true
versionRange="[15.0.4-beta,)"
ordering="AFTER"
side="BOTH"
[[dependencies.ae2additions]]
modId="mekanism"
mandatory=false
ordering="AFTER"
versionRange="[10.3.3,)"
side="BOTH"
[[dependencies.ae2additions]]
modId="appmek"
mandatory=false
ordering="AFTER"
versionRange="[1.3.1,)"
side="BOTH"
[[dependencies.ae2additions]]
modId="ae2things"
mandatory=false
ordering="AFTER"
versionRange="[1.0.0,)"
side="BOTH"
[[dependencies.ae2additions]]
modId="ftbteams"
mandatory=false
ordering="AFTER"
versionRange="[2001.1.4,)"
side="BOTH"